#!/bin/bash
DIR=$(dirname "$0")
cd "$DIR"
clear


~/GitHub/Insoft-UK/scripts/version_code.sh
make -j$(sysctl -n hw.ncpu) all

# Close the Terminal window
osascript -e 'tell application "Terminal" to close window 1' & exit
